### ISSUE TITLE
Wild Pokemon always have quiet nature

### ISSUE THREAD

**Issue by tanthon1** [resetes12/pokeemerald#10]
Hi I made a post about this on PokeCommunity, thought I had it solved, but it seems to still be an issue. Basically, every single wild pokemon I catch has the Quiet nature and I have no idea why.

I'm incredibly confused because I can assume from forum posts that I may be the only one having this issue. But I've tried with two different roms, an emulator and VC inject on the 3DS and all are having the same issue. The only constant is that I'm playing on my 3DS.

The romhack also seems to be incompatible with PKSM (leads to corrupt save file message), meaning I can't manually edit pokemon's nature. I can provide pictures if needed to prove.

**Comment by resetes12** [comment]
I just tested this and, as expected, I can't replicate the issue. Both with a new file and an older file generated in 1.3,

First of all, it's impossible to open the savefile with PKSM as this hackrom modifies structures that external programs can't read.

Secondly, I need more information:

- Does it happen if you take a clean ROM, but on PC's mGBA?
- Does it happen if you take your ROM, and your savefile, but on PC's mGBA?
- Which challenges and extra options do you have enabled?
- Have you tried if this happens after starting a new game?

Other than that, there's not much else I can do right now.

**Comment by tanthon1** [comment]
First of all, thank you for your quick response and for testing. I wasn't aware that Gen 8 Synchronize was added to the romhack (I didn't play Gen 8 so I also didn't know that was a thing). That has to be the issue. I'll go ahead and close, thank you!!
