### ISSUE TITLE
30/31 option for Player IVs

### ISSUE THREAD

**Issue by delipunch** [resetes12/pokeemerald#16]
Can a third option for Player IVs be added, where IVs are randomly either 30 or 31 for each stat? This would let Hidden Power be used as normal while still keeping in the spirit of the all-31 mode.

Could be implemented by ORing the RNG'd IV values for a new 'Mon with 0b11110/0x1E to ensure the IV is 30 (0b11110/0x1E) or 31 (0b11111/0x1F).

**Comment by resetes12** [comment]
Not a bad suggestion so I'll add it to the list. 

You are also free to do a pull request.

**Comment by delipunch** [comment]
Added with 2.0
