### ISSUE TITLE
Many Suggestions

### ISSUE THREAD

**Issue by MaximoMidnight** [resetes12/pokeemerald#17]
Hello, first and foremost, I would like to express my heartfelt gratitude. This version of Pokémon Emerald is simply the best I have been able to find so far. It includes so many innovations and is just incredibly well executed. I have a tremendous amount of fun playing it and I can't seem to stop. I would like to provide some suggestions that, at least for me, would further enhance the gaming experience.

• Change the battle backgrounds. In Pokémon Emerald DX, there are incredibly good battle backgrounds that are just realistic and fit perfectly into the game. When I'm fishing at the beach, I see the sea and the beach, and when I'm in a cave, I see rocks and so on. I would really love it if your version also had these backgrounds during battles.

• Access to the PC without DEBUG. While it is possible to access the PC outside of a Pokémon Center, I can only store Pokémon there, but not move them back and forth. It would be incredibly convenient if I could switch my Pokémon in a cave without having to leave it.

• Unlimited Wonder Trade. So far, Wonder Trade is limited to 3 Pokémon per day. I find this very unfortunate because I really enjoy trading, and often it's even bugged and I can only trade 1 Pokémon and then have to wait. I think it's more fun without any limitations.

• Optional and I'm not sure if it's still implementable, but in Pokémon Quezal, it is possible to see the Pokémon in the grass, just like in modern titles. Something like that would be really cool, but it's probably difficult to integrate.

• Trading Pokémon earlier. So far, I have to wait a long time before I can trade my Pokémon myself. I would like it if this were possible after obtaining the 3rd badge.

• Depositing eggs in the Day Care on the PC when the team is full. It would be incredibly convenient if every egg could automatically be sent to the PC when the team is full. This way, you can breed more Pokémon without having to go in every time.

I hope you read through everything, so far I haven't been able to find any errors except for the Wonder Trade. I've managed to find 6 Shinies so far with the 1/520 rate. Is that normal?

My first wish is the most important one; the battle backgrounds make such a difference and make the game so much better. Please consider it. The backgrounds are easily found on Reddit and can be easily integrated by a programmer.

Thank you very, very much, I would like to support your work. Just tell me how.

Best regards
![42902_a299ca7d9f7fa343e17fb29749d7be2137642a4b](https://github.com/resetes12/pokeemerald/assets/33175850/e039f8a9-e566-4e3c-89cf-b0a4800088ef)

**Comment by resetes12** [comment]
Hey! Those are some neat suggestions, thanks! However:

1. Battle backgrounds are out of the scope of the project. Although it does at certain points, this rom doesn't focus on graphically enhancing the original game.
2. This is a byproduct of the debug menu being quite old. I'm not planning on adding any "access PC from outside a Pkm center"
3. Working on it.
4. Nope, outside of the scope of the project. 
5. Will have to think about it.
6. This could be a good addition.

And yes, shinies are super duper common with 1/512 shiny rate.

**Comment by TonyLaV** [comment]
Thank you for expanding the game even more. I have another Suggestion.

- Seen all Pokemon Feature.
It would be great, if i could choose, if my Dex already seen all Pokis, so its easier for me to find them all. Till now, i have to use you Docu each time, but it would be better if i could use my Dex for it.

**Comment by dejalavidavolar** [comment]
Hi! I really love this hackrom, and I want to say thank you for all your work on it.

About this:
>     1. Battle backgrounds are out of the scope of the project. Although it does at certain points, this rom doesn't focus on graphically enhancing the original game.

Maybe, if it would be possible to add it optionally? I mean, with a toggle option in menu? I understand that changing battle backgrounds to custom ones by default is not an option to people who wants to play in vainilla style, but if it would be a way to change in menu, it would be great! (Pokemon emerald DX has really nice battle backgrounds).

Btw, i would like to add another suggestion: When i use pokemon with habilities like "Trace" (f.e: Ralts), text in-battle it s so fast, even if i have "slow text speed" in settings. I don't know if it happens with habilities like "Frisk" or another ones, but I can't read in time :(.

That's all! Best Greetings, I m enjoying this hackrom a lot!

**Comment by MaximoMidnight** [comment]
I can fully agree with that. Of course, it's up to the developer, but these backgrounds enhance the game so immensely that it's simply a must-have. From what I can see, some have already been replaced, so it would be really great if either this option is added or integrated directly. It's such a beautiful gaming experience with these backgrounds, and it adds so much more value to your work than it already has.

**Comment by MaximoMidnight** [comment]
I'm sorry, unfortunately, I have no idea how to edit Gameboy ROMs. I've tried, but you know more about it than I do. I can link you to the site with the files, maybe you just need to "replace" things. You're the pro, so I'll leave it to you. But as I said, for me personally, the only things missing are the backgrounds and possibly the ability to re-challenge other trainers to a battle, like in FireRed. If those two things were included, your ROM would be an absolute dream for me.

https://github.com/danenders/pkedx/tree/main/graphics/battle_terrain

**Comment by dejalavidavolar** [comment]
> First of all, you are using "Fast Battles", which skips all text delays automatically. This is why abilities and similar text are skipped.

Oh, I understand, my bad, sorry!


> Secondly, this hack doesn't enhance any graphics from the original game. I'm open to making this an optional feature, however, I won't work on it as it requires too much work AND (**most importantly**) a good knowledge of pixel art and graphics, which I don't have. If someone wants to do it, I accept pull requests.

I m glad to hear that! I understand, obviously graphic work would be too much, because of that I was talking about (and already mentioned) battle backgrounds from PKEDX. Those are already open-source!

**Comment by resetes12** [comment]
> I'm sorry, unfortunately, I have no idea how to edit Gameboy ROMs. I've tried, but you know more about it than I do. I can link you to the site with the files, maybe you just need to "replace" things. You're the pro, so I'll leave it to you. But as I said, for me personally, the only things missing are the backgrounds and possibly the ability to re-challenge other trainers to a battle, like in FireRed. If those two things were included, your ROM would be an absolute dream for me.
> 
> https://github.com/danenders/pkedx/tree/main/graphics/battle_terrain

> > First of all, you are using "Fast Battles", which skips all text delays automatically. This is why abilities and similar text are skipped.
> 
> Oh, I understand, my bad, sorry!
> 
> > Secondly, this hack doesn't enhance any graphics from the original game. I'm open to making this an optional feature, however, I won't work on it as it requires too much work AND (**most importantly**) a good knowledge of pixel art and graphics, which I don't have. If someone wants to do it, I accept pull requests.
> 
> I m glad to hear that! I understand, obviously graphic work would be too much, because of that I was talking about (and already mentioned) battle backgrounds from PKEDX. Those are already open-source!

I'm sorry but I'm not going to use their battle terrains. They created those specific backgrounds for their version of Emerald. I wouldn't mind if someone copied some of my stuff from Modern Emerald, but I get that they may not like that. Also Modern Emerald is not Emerald Deluxe.

If anything, I wouldn't mind adding something similar to GEN IV battle terrains. I just checked and tested and it's not very difficult to implement. For example, [this free resource](https://github.com/Pawkkie/Team-Aquas-Asset-Repo/tree/main/Battle%20Backgrounds/RavePossum) (which is shared and not directly copied from another project) fits the project:

![battle_bgs](https://github.com/resetes12/pokeemerald/assets/67122715/e77d125b-d0cf-4b7a-98a7-5fcbaa9c90d7)

- It retains the lines background, so GEN 3 aesthetics are still in place.
- Modernizes the "circular" battle terrain.

**Comment by dejalavidavolar** [comment]
> > I'm sorry, unfortunately, I have no idea how to edit Gameboy ROMs. I've tried, but you know more about it than I do. I can link you to the site with the files, maybe you just need to "replace" things. You're the pro, so I'll leave it to you. But as I said, for me personally, the only things missing are the backgrounds and possibly the ability to re-challenge other trainers to a battle, like in FireRed. If those two things were included, your ROM would be an absolute dream for me.
> > https://github.com/danenders/pkedx/tree/main/graphics/battle_terrain
> 
> > > First of all, you are using "Fast Battles", which skips all text delays automatically. This is why abilities and similar text are skipped.
> > 
> > 
> > Oh, I understand, my bad, sorry!
> > > Secondly, this hack doesn't enhance any graphics from the original game. I'm open to making this an optional feature, however, I won't work on it as it requires too much work AND (**most importantly**) a good knowledge of pixel art and graphics, which I don't have. If someone wants to do it, I accept pull requests.
> > 
> > 
> > I m glad to hear that! I understand, obviously graphic work would be too much, because of that I was talking about (and already mentioned) battle backgrounds from PKEDX. Those are already open-source!
> 
> I'm sorry but I'm not going to use their battle terrains. They created those specific backgrounds for their version of Emerald. I wouldn't mind if someone copied some of my stuff from Modern Emerald, but I get that they may not like that. Also Modern Emerald is not Emerald Deluxe.
> 
> If anything, I wouldn't mind adding something similar to GEN IV battle terrains. I just checked and tested and it's not very difficult to implement. For example, [this free resource](https://github.com/Pawkkie/Team-Aquas-Asset-Repo/tree/main/Battle%20Backgrounds/RavePossum) (which is shared and not directly copied from another project) fits the project:
> 
> ![battle_bgs](https://private-user-images.githubusercontent.com/67122715/320655743-e77d125b-d0cf-4b7a-98a7-5fcbaa9c90d7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTM4MzMsIm5iZiI6MTcxMjYxMzUzMywicGF0aCI6Ii82NzEyMjcxNS8zMjA2NTU3NDMtZTc3ZDEyNWItZDBjZi00YjdhLTk4YTctNWZjYmFhOWM5MGQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDIxNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOWMwZDM5Y2U0ODQ3NzNlOTlkNTQxNTQzMTRmZDJhOTJkMzc1OWM1NzU5NmQ4YWU5OTU4OWI5YzZjY2JlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x5JzPORoAcUa0HyEWl0qYHUNySHXgPrIULzZZI8r5Ps) [ ](https://private-user-images.githubusercontent.com/67122715/320655743-e77d125b-d0cf-4b7a-98a7-5fcbaa9c90d7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTM4MzMsIm5iZiI6MTcxMjYxMzUzMywicGF0aCI6Ii82NzEyMjcxNS8zMjA2NTU3NDMtZTc3ZDEyNWItZDBjZi00YjdhLTk4YTctNWZjYmFhOWM5MGQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDIxNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOWMwZDM5Y2U0ODQ3NzNlOTlkNTQxNTQzMTRmZDJhOTJkMzc1OWM1NzU5NmQ4YWU5OTU4OWI5YzZjY2JlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x5JzPORoAcUa0HyEWl0qYHUNySHXgPrIULzZZI8r5Ps) ![battle_bgs](https://private-user-images.githubusercontent.com/67122715/320655743-e77d125b-d0cf-4b7a-98a7-5fcbaa9c90d7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTM4MzMsIm5iZiI6MTcxMjYxMzUzMywicGF0aCI6Ii82NzEyMjcxNS8zMjA2NTU3NDMtZTc3ZDEyNWItZDBjZi00YjdhLTk4YTctNWZjYmFhOWM5MGQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDIxNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOWMwZDM5Y2U0ODQ3NzNlOTlkNTQxNTQzMTRmZDJhOTJkMzc1OWM1NzU5NmQ4YWU5OTU4OWI5YzZjY2JlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x5JzPORoAcUa0HyEWl0qYHUNySHXgPrIULzZZI8r5Ps) [ ](https://private-user-images.githubusercontent.com/67122715/320655743-e77d125b-d0cf-4b7a-98a7-5fcbaa9c90d7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTM4MzMsIm5iZiI6MTcxMjYxMzUzMywicGF0aCI6Ii82NzEyMjcxNS8zMjA2NTU3NDMtZTc3ZDEyNWItZDBjZi00YjdhLTk4YTctNWZjYmFhOWM5MGQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDIxNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOWMwZDM5Y2U0ODQ3NzNlOTlkNTQxNTQzMTRmZDJhOTJkMzc1OWM1NzU5NmQ4YWU5OTU4OWI5YzZjY2JlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x5JzPORoAcUa0HyEWl0qYHUNySHXgPrIULzZZI8r5Ps)
> 
>     * It retains the lines background, so GEN 3 aesthetics are still in place.
> 
>     * Modernizes the "circular" battle terrain.

That's completely understandable. That free resource looks great! And you are right, gen 3 aesthetics are still there.
Thanks for your answers. 

Greetings!
