### ISSUE TITLE
Wrong Level Cap for Tate & Liza

### ISSUE THREAD

**Issue by fanyx** [resetes12/pokeemerald#18]
I just got to Mossdeep around level 39-43 on Hard Mode using Hard Level Caps.
Tate and Liza's Team is as following on Hard Mode (for me):
- Xatu Lv 47
- Claydol Lv 47
- Solrock Lv 48
- Lunatone Lv 48

If i read correctly that should result in the level cap being at Lv 47?
I cannot by any means train my pokemon beyond Lv 44 for some reason.

I can list my full options or attach the savegame if needed but this *feels* bugged in either the ROM or my savegame.

**Comment by resetes12** [comment]
Hey! You are right! Level caps weren't updated when I updated the level scaling long time ago. Sorry about it!

**Comment by fanyx** [comment]
Thanks for the quick fix! <3
Looking forward to 1.5.7 then i guess ^^

**Comment by resetes12** [comment]
Sadly, even if you compile the code, the save game won't be compatible. The best option would be to enable debug, and disable hard level-caps.

**Comment by fanyx** [comment]
No worries, i beat the fight on Lv 44!
Continuing to the double battle with Steven against Maxie and Tabitha though, it also seems like Steven's pokemon are very low level? (Around 43, compared to Maxie's Lv 48-50)

Could it be they're also still scaled to Normal difficulty?
