### ISSUE TITLE
Nuzlocke without Fly

### ISSUE THREAD

**Issue by PaperFixie** [resetes12/pokeemerald#2]
I’m running into an issue in Nuzlocke mode where I have access to Fly, but my only Pokémon who could use it is fainted.

Is there some way to make a workaround for if you don’t have access to an HM that you can either catch a Pokémon who can use it or designate a Pokémon as an HM user? The idea would be that neither are eligible to battle, so it shouldn’t change the run significantly aside from being able to access the move?

**Comment by resetes12** [comment]
Hey! I might add an item that enables fly for Nuzlocke runs. What about other HMs? I don't like playing Nuzlocke, so I would appreciate your comments about it.

**Comment by fancythedeveloper** [comment]
> Hey! I might add an item that enables fly for Nuzlocke runs. What about other HMs? I don't like playing Nuzlocke, so I would appreciate your comments about it.

Honestly, considering Modern Emerald is mainly supposed to be a QoL hack, I think it would be really useful to implement item-based versions of the HMs or at least allow us to use them without having to teach them. It's always nice being able to go through a region without wasting precious move slots on usually useless moves like Rock Smash.

**Comment by resetes12** [comment]
> > Hey! I might add an item that enables fly for Nuzlocke runs. What about other HMs? I don't like playing Nuzlocke, so I would appreciate your comments about it.
> 
> Honestly, considering Modern Emerald is mainly supposed to be a QoL hack, I think it would be really useful to implement item-based versions of the HMs or at least allow us to use them without having to teach them. It's always nice being able to go through a region without wasting precious move slots on usually useless moves like Rock Smash.

That's already in the game though. You can use HMs if you have a Pokémon that can learn that HM on the team. Having HM items for every run would invalidate completely HMs, and that would be the same as not having them.

**Comment by PaperFixie** [comment]
I found a “bug” then after I submitted this issue. When I went to my first
party Pokémon had Fly available regardless of their ability to learn it or
having a Pokémon who could learn it party.

So maybe it’s already solved for and just needs something more formalized?
Personally, if Fly was just an option in the PokéNav, that would be the
best.

**Comment by resetes12** [comment]
Looks like the game has a fail-safe for Nuzlocke runs so you can use HMs everywhere, even if your Pokémon is fainted. If you have the correct badges, and if you have the HMs in your bag, you will be able to use HMs even if you don't have a Pokémon who cannot learn those HM moves.
Of course, this means that you will see strange things like Pokémon that cannot do Surf doing Surf, or having Fly in Pokémon that cannot fly, but it's a working solution which I did not know.

The code for the Nuzlocke (and other challenges) was not made by me, so I didn't know about that.
