### ISSUE TITLE
RARECANDY

### ISSUE THREAD

**Issue by pepitoxxxx09090** [resetes12/pokeemerald#20]
First of all, thanks for the work!
My question is: is there a way to get as many rarecandies as I want as an in game mechanics?
Thank you again!

**Comment by TonyLaV** [comment]
Oldale Town - There is a girl on the right. Speak with her, she gives you a Box with unlimited Rare Candys and repels.

**Comment by pepitoxxxx09090** [comment]
Thanks for the quick reply!
I spoke to everybody in Oldale and doesn't seem to work.. I attached an image of the npc i thought would give me the rarecandies
![Captura de pantalla 2024-03-19 a las 19 37 15](https://github.com/resetes12/pokeemerald/assets/164067253/5e8069f5-078a-453c-b47e-489e138fbdc3)

**Comment by resetes12** [comment]
You may be using an older version. 1.4.1 added this feature.
