### ISSUE TITLE
ROM not working with MyBoy! 

### ISSUE THREAD

**Issue by TonyLaV** [resetes12/pokeemerald#21]
Hello , 

i just upgraded and i finally wanted to start. But with MyBoy im not longer able to play the game on Android ( Screen stays white ). With PC Emulator it starts without Problem. Do you have an tip for me, how to solve this problem or any other recommentation?

**Comment by TonyLaV** [comment]
I fixed it, nvm.

**Comment by delipunch** [comment]
> I fixed it, nvm.

PLEASE, PLEASE, PLEASE! Don't do this, don't be [DenvorCoder9](https://xkcd.com/979/)! Please explain how you fixed it, this time and every time after. You never know when someone else may need this info.
