### ISSUE TITLE
Access PC broken

### ISSUE THREAD

**Issue by MaximoMidnight** [resetes12/pokeemerald#22]
After the update, this function is now bugged. It creates strange objects on the map and does not run flawlessly; it lags, etc. After using it, you can't get past the frame it created that object. You have to leave the area and come back again to remove it.

**Comment by TonyLaV** [comment]
Still not fixed, see Screenshot
![pokemon](https://github.com/resetes12/pokeemerald/assets/33175850/c6cd6d9f-7a69-492e-a5d5-71f07cd2ef9e)

**Comment by resetes12** [comment]
The PC is used as a debug feature, not as an actual gameplay feature. 
2.0 added the option to use the full PC, but it creates strange tiles. Although this shouldn't happen, you are not expected to use the PC as a common option. If you are using debug features, you should know they can cause issues.

**Comment by MaximoMidnight** [comment]
Did you manage to do something to fix the tiles? They were not there before 2.0. It was one of the reasons i enjoyed your version soo much.
