### ISSUE TITLE
Skip "dry battery" message when Fake RTC is enabled.

### ISSUE THREAD

**Issue by delipunch** [resetes12/pokeemerald#25]
If a save exists with the Fake RTC enabled, the game should skip the message about the RTC battery being dry immediately after the title screen, as it's now redundant.

It should specifically check for the save file like that, so on a first boot on an new emulator or flash cart with no RTC functionality, the user can be warned that they'll need the Fake RTC options for time to work in a new file. If a save file has the normal RTC setting, it should still display the message when applicable.

**Comment by delipunch** [comment]
Changing [`
pokeemerald/src/main_menu.c
` line 753](https://github.com/resetes12/pokeemerald/blob/e0b1c3d5f088d20c9650bc5c47fc75c6635acce8/src/main_menu.c#L753C9-L753C56), from 
```if (!(RtcGetErrorStatus() & RTC_ERR_FLAG_MASK))```
to
```if (!(RtcGetErrorStatus() & RTC_ERR_FLAG_MASK) || gSaveBlock1Ptr->tx_Features_RTCType == 1)```
should do this, right?

**Comment by resetes12** [comment]
[Done](https://github.com/resetes12/pokeemerald/commit/cf07fb25775abce933048fc368fb7f4ecc1ffa1e).

The game now checks if Fake RTC is enabled. If not, it will print the battery dry error (now saying that Fake RTC is recommended with no battery). If it's enabled, it will skip the error.
