### ISSUE TITLE
Starter selection screen crashes RetroArch gpSP core

### ISSUE THREAD

**Issue by delipunch** [resetes12/pokeemerald#28]
Title. Some platforms RA is on has the gpSP core but not the mGBA core, tested with RA on Steam on Win11, RetroFW on a RS-97 handheld (this particular platform lacks mGBA), and RRVL on an Odroid Go Advance v1.1.

**Comment by resetes12** [comment]
[Modern Emerald on based on pokeemerald, from Pret. They are the ones who handle these issues, as that is the main project. Please report to them.](https://github.com/pret/pokeemerald). I have zero control over these issues.

**Comment by delipunch** [comment]
Petitioning to reopen - starter selection works as intended in 1.5.6, and I believe 2.0 is the first version with the bug. Therefore it's not an upstream issue.

**Comment by resetes12** [comment]
From 1.5.6 to 2.1 pokeemerald has been updated pretty thoroughly, with nearly a year's worth of updates. Again, I have zero control over emulator issues. 
If it happened in every emulator, then yeah, it'd be my issue. If I had updated the starter selection, then yeah, It might have been my issue. Not the case.
