### ISSUE TITLE
Can't talk to Nurse Joy in Pokemon Center

### ISSUE THREAD

**Issue by walkawayy** [resetes12/pokeemerald#31]
If I press A (or L as A) to talk to Nurse Joy, my character just turns around instead. I can still heal by depositing and withdrawing from the PC, but not being able to use the Pokecenter is a huge issue. The issue started in Petalburg City after I changed the difficulty from Hard to Normal. Maybe that change messed something up? I tried previous Pokecenters, but the same bug occurred. It was working yesterday when I played. This is a first time playthrough on the newest 2.3 version.

https://github.com/resetes12/pokeemerald/assets/81546780/efaaa917-533a-4379-9fd4-4b6bace5c851

**Comment by resetes12** [comment]
There is no bug. You have enabled "Even faster joy", which removes any animation from Joy's healing.
