### ISSUE TITLE
Can't Reach Mewtwo and Daily Events

### ISSUE THREAD

**Issue by Starblast16** [resetes12/pokeemerald#33]
Two Issues I've noticed. When I went after Mewtwo, I found that the section of water you have to surf on to reach it has no collision and you can't surf on it. Also the stairs that lead to Mewtwo act like a wall. As for the other issue, I've noticed that I haven't had any of the timed events and outbreaks trigger for well over a week now.

**Comment by resetes12** [comment]
Mewtwo's collision issues were fixed yesterday with 2.3.1 release.
I have no comment on outbreaks and timed events, as I have seen them work. Using Fake RTC may make them last for a short time since they rely on the RTC which is faster with that option.

**Comment by Starblast16** [comment]
I'm using regular RTC. And I wasn't aware of that update until now.
