### ISSUE TITLE
Can’t talk to nurse joy

### ISSUE THREAD

**Issue by michyprima** [resetes12/pokeemerald#39]
Hey so basically I just reached the first pokemon center in oldale town and can’t seem to talk to the nurse to heal. 

https://github.com/resetes12/pokeemerald/assets/4800403/09aeed86-f686-4530-9e30-4a39b85b19f4

**Comment by MaximoMidnight** [comment]
https://github.com/resetes12/pokeemerald/issues/31

Please read description or already closed topics.

This should explain your issue

**Comment by michyprima** [comment]
Oh damn sorry that was it! May I suggest to add a sound so you actually know healing was done? Like the sound when you use a potion

**Comment by resetes12** [comment]
> Oh damn sorry that was it! May I suggest to add a sound so you actually know healing was done? Like the sound when you use a potion

That's actually a great idea and will be implemented in the next version. Thank you!
