### ISSUE TITLE
Patching from 1.5.6 to 2.0 corrupts the save file

### ISSUE THREAD

**Issue by tinjus123** [resetes12/pokeemerald#41]
As the title says, 2.0 patch corrupts game save from a 1.5.6 patch. I individually patched the roms from 1.4 to 1.5.6 to make sure that the transtion between patches were smooth. When I got to 2.0 patch my old save wasn't read properly and it said that it was corrupted. I know there were many options update that was implemented on 2.0 so I thought that might be the problem. Has anyone encountered the same problem?

**Comment by resetes12** [comment]
2.0 needs a new savefile, as the save structure has changed. I recommend trading the Pokémon from 1.5.6 to +2.0.
