### ISSUE TITLE
No Updates anymore? 

### ISSUE THREAD

**Issue by MaximoMidnight** [resetes12/pokeemerald#44]
Hello,

i waited for months now for the new version you announced. 

Many people asked you something and got no response. 

Is this hack finished or are you afk for longer time? 

I did not want to start a new game because every update could break the save. 

But if this hack is not longer developed, i can play withouth worries and anybody who visits your site knows its dead / finished. 

So , if you have any news, your fans will be glad to hear smt. Its a really good hack and thank you again for it. 

Greetings

**Comment by resetes12** [comment]
I'm extremely busy and I can't dedicate time to the project. I'm still gathering new ideas and stuff, but rest assured that I don't plan on adding anything that would break save files again so you can play without any worries.
