### ISSUE TITLE
Error when building with Make: 

### ISSUE THREAD

**Issue by NeoGC** [resetes12/pokeemerald#7]
Hey there! Looking to possibly look into doing some of the legwork of decapitalizing Modern Emerald and seeing if I'm up to the task. 

I'm trying to do a build of `pokeemerald.gba` just as a test to make sure I have a means of testing my work, but when I use 'make' to build, I run into this error inside `src/battle_controller_player.c.

`src/battle_controller_player.c: In function ``TypeEffectiveness':
src/battle_controller_player.c:1605: syntax error before struct'
src/battle_controller_player.c:1606: moveInfo' undeclared (first use in this function)
src/battle_controller_player.c:1606: (Each undeclared identifier is reported only once
src/battle_controller_player.c:1606: for each function it appears in.)
make: *** [Makefile:343: build/emerald/src/battle_controller_player.o] Error 1
make: *** Deleting file 'build/emerald/src/battle_controller_player.o'`

I moved the struct define to above the if statement on line 1602 on the suggestion of someone inside the Pret discord server, but unfortunately I run into further build issues on other scripts, such as the Battle Frontier script canceling the build due to non-explicit usage of curly brackets...

![image](https://github.com/resetes12/pokeemerald/assets/49330079/22aa3a96-5a53-4c5e-a09e-98881e1fee69)

**Comment by resetes12** [comment]
Modern Emerald is built using `make modern`. iirc, it'll spit these errors if you try to build the ROM without it.

**Comment by PinkShellos** [comment]
@resetes12 I hit the same error before I figured that out. Could you potentially modify the README to include that? 

If you’re using macOS, install make using homebrew (‘brew install make’). My M3 Mac threw errors until I did that. Then you can run the build using ‘gmake modern’

**Comment by NeoGC** [comment]
That seems to get me further along in, but then I run into some further issues.

Now, I'm no linux expert by any stretch of the imagination, but what it looks like is some missing dependencies 
![image](https://github.com/resetes12/pokeemerald/assets/49330079/17913132-df6d-4cad-970f-c347ba060075)

I tried installing the GNU Arm Embedded Toolchain via the tar.bz2 but it didn't seem to move the needle.

**Comment by PinkShellos** [comment]
Looks like you may need devkitARM installed. I had to follow [this guide](https://github.com/pret/pokeemerald/blob/master/INSTALL.md#installing-devkitarm-on-debianubuntu-based-distributions) from Pret. After I did that it compiled for me.

**Comment by NeoGC** [comment]
> Looks like you may need devkitARM installed. I had to follow [this guide](https://github.com/pret/pokeemerald/blob/master/INSTALL.md#installing-devkitarm-on-debianubuntu-based-distributions) from Pret. After I did that it compiled for me.

Unfortunately, I believe that tutorial step is outdated. The only available binary from https://github.com/devkitPro/pacman/releases is `devkitpro-pacman-installer.pkg.`

The .deb is nowhere to be found.
