### ISSUE TITLE
"Hidden Power" effectiveness is shown incorrectly when "Type effectiveness" is ON

### ISSUE THREAD

**Issue by resetes12** [resetes12/pokeemerald#8]
Hidden power works, and shows the correct typing but the "Type effectiveness" option found in the options menu still thinks this move is Normal type. Doesn't affect gameplay in any way.

![pokeemerald_modern-0](https://github.com/resetes12/pokeemerald/assets/67122715/de5e0cda-9c1c-42ad-8ba0-9db4361bba52)

**Comment by PinkShellos** [comment]
I'm looking into this now, but I'm not finding where Hidden Power calculates its typing. Could you point to where that is located?

Thanks!

**Comment by resetes12** [comment]
Doesn't seem to work, sadly.

**Comment by PinkShellos** [comment]
Bummer. I’ll give it another go in a bit.

**Comment by PinkShellos** [comment]
Just got it working! PR incoming soon!
